// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 622,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 136,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 410,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1318,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1244,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1318,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1244,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 932,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 932,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1567,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1174,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1174,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1318,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1318,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 1174,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1108,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1318,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1244,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1318,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1244,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 932,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 932,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 1567,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 1479,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 1174,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 273,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 1091,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 1091,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 123,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 92,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 819,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 1091,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 123,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 69,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 92,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 819,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1637,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 1636,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 2182,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 2182,
    },
];
