// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1650,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1050,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 900,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1350,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 41550,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1050,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 900,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1350,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2400,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1050,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2550,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 450,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2550,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 450,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 450,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 5100,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 2700,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 8100,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1050,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 2550,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 7350,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1650,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1350,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1650,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1950,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 7650,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 450,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1050,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 8850,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 450,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1050,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1650,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3900,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 450,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3000,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6000,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 450,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 87,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3000,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2400,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 2700,
    },
];
