// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2760,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 720,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1440,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 720,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 587,
        vol: 60,
        duration_ms: 960,
    },
    Note {
        freq: 523,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2160,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 720,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 960,
    },
    Note {
        freq: 493,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2880,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 960,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1320,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 493,
        vol: 44,
        duration_ms: 720,
    },
    Note {
        freq: 523,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1440,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 523,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 554,
        vol: 44,
        duration_ms: 720,
    },
    Note {
        freq: 587,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 523,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 415,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1080,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 840,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 391,
        vol: 44,
        duration_ms: 720,
    },
    Note {
        freq: 523,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 523,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 415,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 415,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 466,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 440,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 587,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 587,
        vol: 60,
        duration_ms: 160,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 160,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 160,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1200,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 720,
    },
    Note {
        freq: 391,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 493,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 523,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 466,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 440,
        vol: 60,
        duration_ms: 480,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1440,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2040,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 360,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2880,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 8400,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 293,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 5520,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 293,
        vol: 44,
        duration_ms: 240,
    },
    Note {
        freq: 261,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 261,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 240,
    },
    Note {
        freq: 261,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 261,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 480,
    },
    Note {
        freq: 261,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 329,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1680,
    },
    Note {
        freq: 261,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2040,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 261,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 369,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 261,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 369,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2880,
    },
    Note {
        freq: 261,
        vol: 44,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 369,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3240,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 329,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 360,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 120,
    },
    Note {
        freq: 349,
        vol: 44,
        duration_ms: 720,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1680,
    },
    Note {
        freq: 369,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 120,
    },
    Note {
        freq: 369,
        vol: 44,
        duration_ms: 360,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6840,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 720,
    },
    Note {
        freq: 329,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 720,
    },
    Note {
        freq: 329,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 277,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 293,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 960,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1680,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 240,
    },
    Note {
        freq: 293,
        vol: 60,
        duration_ms: 720,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 720,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 360,
    },
    Note {
        freq: 293,
        vol: 60,
        duration_ms: 120,
    },
    Note {
        freq: 261,
        vol: 60,
        duration_ms: 480,
    },
    Note {
        freq: 293,
        vol: 60,
        duration_ms: 360,
    },
    Note {
        freq: 329,
        vol: 60,
        duration_ms: 120,
    },
    Note {
        freq: 349,
        vol: 60,
        duration_ms: 960,
    },
];
