// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 136,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 410,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 272,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 546,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 818,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 136,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1910,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 409,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 818,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 818,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 410,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 136,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 273,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 410,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1091,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 477,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 136,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 69,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1773,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 137,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 136,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 819,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1364,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 136,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 818,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 410,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 1363,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 137,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 818,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 409,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 818,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 545,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1364,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 273,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 4500,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 409,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 682,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1568,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 68,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1159,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 410,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 272,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1091,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 546,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 409,
    },
];
