// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 375,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 125,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 1250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 375,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 125,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 375,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 125,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 1250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 375,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 125,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1000,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 750,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 188,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 987,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 739,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 750,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 63,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 62,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 188,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 500,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1500,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 250,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 123,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 1000,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 123,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 500,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 250,
    },
    Note {
        freq: 97,
        vol: 50,
        duration_ms: 500,
    },
];
