// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 112,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 164,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 174,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1800,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 262,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 562,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 2700,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 262,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 188,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 112,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 188,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 112,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 188,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1800,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 262,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 225,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 375,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 600,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 825,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 525,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 525,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1950,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 675,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 338,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 113,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 112,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 563,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 112,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 225,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 113,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 562,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 563,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 112,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 188,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 2400,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 262,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 562,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 112,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 562,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 38,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 188,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 225,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 188,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 112,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2512,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 2100,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 525,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 450,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 525,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 72,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 4650,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 392,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 149,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 145,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 145,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 18,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1801,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 285,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 148,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 147,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 597,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 297,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 145,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 2702,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 11,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 306,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 148,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 146,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 145,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 602,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1803,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 285,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 148,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 147,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 447,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 297,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 616,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 905,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 605,
    },
    Note {
        freq: 311,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1200,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 589,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 294,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 298,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 299,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 297,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 592,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 78,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 1950,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 691,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 293,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 221,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 895,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 148,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 596,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1195,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 597,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 147,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 148,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 596,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 1195,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 466,
        vol: 50,
        duration_ms: 597,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 147,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 145,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 150,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 11,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 148,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 2402,
    },
    Note {
        freq: 415,
        vol: 50,
        duration_ms: 298,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 147,
    },
    Note {
        freq: 493,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 147,
    },
    Note {
        freq: 554,
        vol: 50,
        duration_ms: 602,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 659,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 111,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 880,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 329,
        vol: 50,
        duration_ms: 582,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 14,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 142,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 14,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 148,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 146,
    },
    Note {
        freq: 587,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 148,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 440,
        vol: 50,
        duration_ms: 149,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 146,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 147,
    },
    Note {
        freq: 293,
        vol: 50,
        duration_ms: 2247,
    },
    Note {
        freq: 349,
        vol: 50,
        duration_ms: 75,
    },
    Note {
        freq: 369,
        vol: 50,
        duration_ms: 78,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 188,
    },
    Note {
        freq: 523,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 698,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 1046,
        vol: 50,
        duration_ms: 2100,
    },
    Note {
        freq: 783,
        vol: 50,
        duration_ms: 113,
    },
    Note {
        freq: 391,
        vol: 50,
        duration_ms: 187,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1125,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 713,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 787,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 1650,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 733,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1405,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 37,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1311,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 750,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 862,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 225,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 525,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1312,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 600,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1500,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 600,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 525,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 277,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 5100,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 38,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1762,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 35,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 3,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 597,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 225,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 75,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 597,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 225,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 75,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 2,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 598,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 562,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 601,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 37,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 525,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 863,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1800,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 824,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 1201,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 37,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 525,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 2472,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 2100,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 78,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3750,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 3450,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1350,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 525,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 1108,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 151,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 741,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 150,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 764,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 152,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 1634,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 152,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 762,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 152,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 1398,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 39,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 302,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 594,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 293,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1247,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 752,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 915,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 1052,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 241,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 495,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 1053,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 111,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1339,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 11,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 1500,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 889,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 11,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 1489,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 900,
    },
    Note {
        freq: 207,
        vol: 50,
        duration_ms: 11,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 155,
        vol: 50,
        duration_ms: 1189,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 103,
        vol: 50,
        duration_ms: 1200,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 5089,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1805,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 595,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 292,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 591,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 294,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 297,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 592,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 292,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 591,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 294,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 233,
        vol: 50,
        duration_ms: 297,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 592,
    },
    Note {
        freq: 138,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 246,
        vol: 50,
        duration_ms: 294,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 298,
    },
    Note {
        freq: 146,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 591,
    },
    Note {
        freq: 164,
        vol: 50,
        duration_ms: 600,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 17,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 300,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 494,
    },
    Note {
        freq: 174,
        vol: 50,
        duration_ms: 1053,
    },
    Note {
        freq: 184,
        vol: 50,
        duration_ms: 892,
    },
    Note {
        freq: 195,
        vol: 50,
        duration_ms: 1671,
    },
    Note {
        freq: 110,
        vol: 50,
        duration_ms: 1050,
    },
    Note {
        freq: 116,
        vol: 50,
        duration_ms: 1206,
    },
    Note {
        freq: 220,
        vol: 50,
        duration_ms: 233,
    },
    Note {
        freq: 261,
        vol: 50,
        duration_ms: 298,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 492,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 2500,
    },
    Note {
        freq: 130,
        vol: 50,
        duration_ms: 2400,
    },
];
