// generated by scripts/midi_to_rust.py

use crate::buzzer::Note;

pub const TRACK_A: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 4,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 8,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 100,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 97,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 196,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 207,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1002,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 395,
    },
    Note {
        freq: 349,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 440,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 391,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 349,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 207,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 792,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 8,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 100,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 97,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 207,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1002,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 395,
    },
    Note {
        freq: 349,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 440,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 391,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 349,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 207,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 246,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 293,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 329,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 261,
        vol: 49,
        duration_ms: 397,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11188,
    },
    Note {
        freq: 220,
        vol: 49,
        duration_ms: 800,
    },
];

pub const TRACK_B: &[Note] = &[
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 412,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 790,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 11,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 990,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 12,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 198,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1400,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1002,
    },
    Note {
        freq: 174,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 988,
    },
    Note {
        freq: 195,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 207,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 195,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 96,
    },
    Note {
        freq: 195,
        vol: 49,
        duration_ms: 100,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1,
    },
    Note {
        freq: 174,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 12,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 198,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 395,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 195,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 212,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 394,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 4,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 790,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 990,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 12,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 198,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1400,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1002,
    },
    Note {
        freq: 174,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 988,
    },
    Note {
        freq: 195,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 207,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 195,
        vol: 49,
        duration_ms: 199,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 96,
    },
    Note {
        freq: 195,
        vol: 49,
        duration_ms: 100,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 1,
    },
    Note {
        freq: 174,
        vol: 49,
        duration_ms: 197,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 12,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 198,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 395,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 195,
    },
    Note {
        freq: 207,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 212,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 200,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 394,
    },
    Note {
        freq: 164,
        vol: 49,
        duration_ms: 4,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 790,
    },
    Note {
        freq: 130,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6,
    },
    Note {
        freq: 110,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 123,
        vol: 49,
        duration_ms: 794,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6,
    },
    Note {
        freq: 103,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 110,
        vol: 49,
        duration_ms: 794,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6,
    },
    Note {
        freq: 82,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 103,
        vol: 49,
        duration_ms: 794,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6,
    },
    Note {
        freq: 103,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 394,
    },
    Note {
        freq: 130,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6,
    },
    Note {
        freq: 110,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 123,
        vol: 49,
        duration_ms: 794,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 6,
    },
    Note {
        freq: 103,
        vol: 49,
        duration_ms: 800,
    },
    Note {
        freq: 110,
        vol: 49,
        duration_ms: 394,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 10,
    },
    Note {
        freq: 130,
        vol: 49,
        duration_ms: 400,
    },
    Note {
        freq: 0,
        vol: 0,
        duration_ms: 788,
    },
    Note {
        freq: 146,
        vol: 49,
        duration_ms: 800,
    },
];
