import pretty_midi
import sys
import math

def convert_midi_to_rust(midi_file, rust_file):
    try:
        midi_data = pretty_midi.PrettyMIDI(midi_file)
    except Exception as e:
        print(f"[ERR] falha ao abrir arquivo MIDI: {e}")
        return

    all_notes = []
    for inst in midi_data.instruments:
        if not inst.is_drum:
            all_notes.extend(inst.notes)

    if not all_notes:
        print("[ERR] nenhuma nota válida encontrada.")
        return

    time_points = set()

    for note in all_notes:
        time_points.add(note.start)
        time_points.add(note.end)

    time_points = sorted(list(time_points))

    rust_code = "// automatically generated by scripts/midi_to_rust.py\n"
    rust_code += "use crate::buzzer::Note;\n\n"
    rust_code += "pub const GENERATED_SONG: &[Note] = &[\n"

    for i in range(len(time_points) - 1):
        start = time_points[i]
        end = time_points[i+1]
        duration_ms = int((end - start) * 1000)

        if duration_ms == 0:
            continue

        active_notes = [n for n in all_notes if n.start <= start and n.end >= end]
        active_notes = sorted(active_notes, key=lambda n: n.pitch, reverse=True)

        freq_a = 0
        freq_b = 0

        if len(active_notes) > 0:
            pitch_a = active_notes[0].pitch

            while pitch_a < 55:
                pitch_a += 12

            while pitch_a > 100:
                pitch_a -= 12

            freq_a = int(440.0 * math.pow(2.0, (pitch_a - 69.0) / 12.0))

        if len(active_notes) > 1:
            pitch_b = active_notes[1].pitch

            while pitch_b < 55:
                pitch_b += 12

            while pitch_b > 100:
                pitch_b -= 12

            freq_b = int(440.0 * math.pow(2.0, (pitch_b - 69.0) / 12.0))

        play_duration = int(duration_ms * 0.95)
        rest_duration = duration_ms - play_duration

        if play_duration > 0:
            rust_code += f"    Note {{ freq_a: {freq_a}, freq_b: {freq_b}, duration_ms: {play_duration} }},\n"
            rust_code += f"    Note {{ freq_a: 0, freq_b: 0, duration_ms: {rest_duration} }},\n"

    rust_code += "];\n"

    try:
        with open(rust_file, "w", encoding="utf-8") as f:
            f.write(rust_code)
    except Exception as e:
        print(f"[ERR] falha ao escrever {rust_file}: {e}")

if __name__ == "__main__":
    args = sys.argv
    if len(args) < 3:
        print("Uso: python midi_to_rust.py <in.mid> <out.rs>")
    else:
        convert_midi_to_rust(args[1], args[2])