import pretty_midi
import sys

def freq_from_pitch(pitch):
    while pitch < 40:
        pitch += 12
    
    while pitch > 100: 
        pitch -= 12
    
    return int(440.0 * (2.0 ** ((pitch - 69.0) / 12.0)))

def make_track(notes, is_bass=False):
    events = sorted(
        [(round(n.start * 1000), 'start', n) for n in notes] + 
        [(round(n.end * 1000), 'end', n) for n in notes],
        key=lambda e: (e[0], e[1] == 'end') 
    )

    merged = []
    active = []
    last_time = 0
    
    selector = min if is_bass else max

    for time, ev_type, note in events:
        dur = time - last_time
        
        if dur > 0:
            selected = selector(active, key=lambda x: x.pitch) if active else None
            freq = freq_from_pitch(selected.pitch) if selected else 0
            vol = selected.velocity if selected else 0
            
            prev = merged[-1] if merged else None
            
            if prev and (prev['ref'] == selected or (prev['freq'] == freq == 0)):
                prev['dur'] += dur
            else:
                merged.append({'freq': freq, 'vol': vol, 'dur': dur, 'ref': selected})
                
        last_time = time
        
        if ev_type == 'start':
            active.append(note)
        elif note in active:
            active.remove(note)

    return merged

def convert_midi_to_rust(midi_file, rust_file):
    try:
        midi_data = pretty_midi.PrettyMIDI(midi_file)
    except Exception as e:
        return print(f"[ERR] falha ao abrir MIDI: {e}")

    all_notes = sorted([n for inst in midi_data.instruments if not inst.is_drum for n in inst.notes], key=lambda x: x.pitch)
    if not all_notes: return

    mid_idx = len(all_notes) // 2
    median_pitch = all_notes[mid_idx].pitch

    melody = [n for n in all_notes if n.pitch >= median_pitch]
    bass = [n for n in all_notes if n.pitch < median_pitch]

    melody, bass = (melody, bass) if bass else (all_notes[mid_idx:], all_notes[:mid_idx])

    track_a = make_track(melody, is_bass=False)
    track_b = make_track(bass, is_bass=True)

    format_note = lambda t: f"    Note {{\n        freq: {t['freq']},\n        vol: {t['vol']},\n        duration_ms: {t['dur']},\n    }},"

    rust_code = (
        "// generated by scripts/midi_to_rust.py\n\n"
        "use crate::buzzer::Note;\n\n"
        "pub const TRACK_A: &[Note] = &[\n" + 
        "\n".join(map(format_note, track_a)) + 
        "\n];\n\n"
        "pub const TRACK_B: &[Note] = &[\n" + 
        "\n".join(map(format_note, track_b)) + 
        "\n];\n"
    )

    with open(rust_file, "w", encoding="utf-8") as f:
        f.write(rust_code)
    print(f"[OK] arquivo gerado")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Uso: python midi_to_rust.py <in.mid> <out.rs>")
    else:
        convert_midi_to_rust(sys.argv[1], sys.argv[2])